version: "3.9"

services:
  alltracker:
    build:
      context: .
      dockerfile: Dockerfile
    image: alltracker:cu128
    container_name: alltracker
    # Mount local folders you want accessible in the container
    volumes:
      - ./demo_video:/app/demo_video
      - ./datasets:/app/datasets
      # Persist model/cache to avoid re-downloading each run
      - ./cache/torch:/root/.cache/torch
      # Optional: mount pre-downloaded checkpoints (put alltracker_tiny.pth here)
      - ./weights:/root/.cache/torch/hub/checkpoints
      # Optional: store outputs on host
      - ./outputs:/app/outputs
    # Request GPU access (Docker Desktop + NVIDIA)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    # Optional shared memory boost for PyTorch/OpenCV workloads
    shm_size: "1g"
    # Default command tuned to reduce VRAM usage
    command: ["bash","-lc","python3 demo.py --mp4_path ./demo_video/monkey.mp4 && mkdir -p outputs && mv pt_vis_*.mp4 outputs/"]
